### PR TITLE
Changes related to template file

### PR DESCRIPTION
**Pull request by Glovania**

### CODE REVIEW

**Comment by RyanCather** [comment]
Before this gets merged... has it been tested?
The changes to Template look good.
Why remove Bootstrap from the project? Your version loads bootstrap from an external site - any reason for the change? The reason for keeping the files local was to still support users connecting through the CyberRange.

**Comment by Glovania** [comment]
> Before this gets merged... has it been tested?

- As far as things I could do when editing this file in a local server (at home), I can confirm that it tested and work. I can't really do any further stress testing because of the limitation I just mentioned. However, as mostly the file I'm changing are re-formatting the codes in a more readable format so it shouldn't (possibly) break anything>

> The changes to Template look good.

- Glad to hear that :D

>  Why remove Bootstrap from the project? Your version loads bootstrap from an external site - any reason for the change? The reason for keeping the files local was to still support users connecting through the CyberRange.

- According to the [^1][Boostrap documentation][https://getbootstrap.com/docs/5.2/getting-started/introduction/], I think it's better to include the CDN version of Boostrap so that we can easily search up the up-to-date styling values that anyone might need to do changes related to UI / UX design. I have also tested this if it does work for different browsers (GG Chrome, Microsoft Edge, Firefox, and Samsung Internet. I don't have Iphone or Macbook to test Apple-related applications) and operating systems (Windows and Linux tested, I don't have a MacOS one). It does work as how it should be with local files. I think I forget to include the Popper CDN links (which works for dropdown styling and such) from Boostrap so can you possibly add it in too? You can search for it from my provided link[^1] 

- And it's actually reduce the project (website) file sizes because we only use one of their CSS file by including those CDN links in, rather than having to load the whole bundles, which we hardly ever use all of them for this project (even when the local file still there).

**Comment by RyanCather** [comment]
Agree with all of your points, but before we get too far further, I want to test this version on our server. So, we'll hold off on merging this until we can test in production.

**Comment by Glovania** [comment]
No worries.

**Comment by Trixelit** [comment]
In testing - Currently this version is located at http://10.177.200.71/CC-test/CyberCity/ .

BREAKING CHANGES:
* The navbar is not rendering correctly - the register and login buttons are stacking on top of each other (Unsure if this is my browser).
* 2d7922f - Due to the PDO logic changes, all instances of $conn in files that use the database need to be changed to $pdo , and in my testing, this new logic has broken the login page. Currently, when correct credentials are entered, the login page flashes the 'incorrect credentials' error message and login is unsuccessful. This could possibly be attributed to the error it is throwing: (Warning: Undefined array key 0 in /var/www/CC-test/CyberCity/website/pages/user/login.php on line 40).

Other pages are untested - I cannot login to test at this stage.
Will try to debug and add a commit to this PR if I can fix it.

**Comment by RyanCather** [comment]
Can $pdo in template.php be renamed to $conn? 
Would that fix the issue?

**Comment by Glovania** [comment]
Addition information for my commitments:

> Can $pdo in template.php be renamed to $conn? Would that fix the issue?

[pdo-connection-template] : https://www.php.net/manual/en/pdo.connections.php

- According to the [PHP example on how to setup a PDO connection][pdo-connection-template], the naming variable for making connections does not need to be set specifically to '$pdo' or '$conn' (or '$dbh' like they do) so @Trixelit, you can safely convert it back to the original version of this file.

> The navbar is not rendering correctly - the register and login buttons are stacking on top of each other (Unsure if this is my browser).

- I got this issue as well when refactoring this file on the local server. I'm using both Firefox and Microsoft Edge to test it at the time of refactoring it. The issue might lie in the fact that we setup the 'Navigation Bar' quite weirdly. I don't want to fix it 'cause it can be fixed fairly easily (?) but I need to talk with the whole UI / UX team first.

> [!NOTE]
> Take a look at some of my comments (TODOs one) for further explanation.

> Currently, when correct credentials are entered, the login page flashes the 'incorrect credentials' error message and login is unsuccessful. This could possibly be attributed to the error it is throwing: (Warning: Undefined array key 0 in /var/www/CC-test/CyberCity/website/pages/user/login.php on line 40).

- I can't really provide any further information about this because I don't have access to the website's actual database from home. However, it might just be because of the changes on the database connection method.

**Review by Trixelit — COMMENTED** [review]
REVIEW AS OF 10:55AM 2/08/24:

Login logic has been fixed, and works on the server, however PHPStorm's local server throws a 'headers already sent (template.php:10)' error.

Readded the logout button and user information to the navbar for admin users.

The navbar does not format correctly, however I am not sure why.
image

**Comment by Glovania** [comment]
I can see the 'Navigation Bar' fixed now, according to what we have discussed in class about the main issue leading to that. Can this be mergeable now?

**Comment by Trixelit** [comment]
I'll let @RyanCather be the judge of this.

Current issues:
* A few navbar items are not aligned across the horizontal lines
* The links in the dropdown menus currently do not work, and when clicked the entire navbar locks up and cannot be clicked

**Comment by Glovania** [comment]
> I'll let @RyanCather be the judge of this.
> 
> Current issues:
> 
>     * A few navbar items are not aligned across the horizontal lines
> 
>     * The links in the dropdown menus currently do not work, and when clicked the entire navbar locks up and cannot be clicked

Okay then.

**Comment by Glovania** [comment]
UPDATE PART 2 - 13/08/24 07:30:00PM:
- I believe I have the successfully fix the second issue. Just need a quick test from the test server at school.

**Comment by Trixelit** [comment]
Given it a test, and it seems to be working on both phpstorm and the server. Merging

**Pull request merged**
